#!/bin/bash
#SBATCH --job-name=aidedx-unit-probe
#SBATCH --partition=plgrid-gpu-a100
#SBATCH --account=plgccbmc15-gpu-a100
#SBATCH --qos=normal
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=64G
#SBATCH --gres=gpu:a100:1
#SBATCH --time=2:00:00
#SBATCH --array=0-2
#SBATCH --output=%x-%A_%a.out
#SBATCH --error=%x-%A_%a.err
#
# Unit-pronunciation probe study (issue #118). Answers a question the 1000-sentence corpus
# CANNOT: how does each TTS engine actually PRONOUNCE a unit abbreviation — expanded
# ("megaelectronvolt"), or letter-spelled ("em-ee-vee")? Whisper normalizes energy units back
# to the string `MeV` regardless of pronunciation, so the transcript is blind to this
# (docs/unit-pronunciation-asr.md §1). This probe measures it acoustically instead, via a
# minimal-pair design generated by scripts/generate-unit-probe.py:
#
#   for each (carrier, unit, value) we synthesize variants that differ ONLY in unit rendering:
#     abbrev  "150 MeV"   expand "150 megaelectronvolt"   letters "150 em e v"   (+ spaced, energy)
#
# The clip duration of the `abbrev` variant then falls near its `expand` sibling (engine expands)
# or near its `letters` sibling (engine letter-spells). scripts/unit-probe-analyze.py does that
# diff LOCALLY after the results are synced back — no GPU needed for the analysis, only for synth.
#
# --- Why an array job: one lane per engine (the thing we're comparing) ---
#   lane 0: Qwen3-TTS, English   (.venv-qwen,        scripts/tts-qwen-1000.py)      probe-en.json
#   lane 1: Piper,     Polish    (.venv-piper,       scripts/tts-piper-1000.py)     probe-pl.json
#   lane 2: Chatterbox, Polish   (.venv-chatterbox,  scripts/tts-chatterbox-1000-pl.py, native)  probe-pl.json
# Qwen(EN) is the neural engine whose transcripts already show `centimeter` expansion; Piper's
# frontend is espeak-ng, which letter-spells everything (docs/unit-pronunciation-asr.md §3);
# Chatterbox(PL) is the newest engine (issue #106) and the least characterized. Each lane is a
# separate SLURM task so a slow/failed engine can't stall the others.
#
# --- Prereqs (same as the sibling submit scripts) ---
# .venv-qwen / .venv-piper / .venv-chatterbox must already exist per docs/athena-setup.md,
# docs/tts-eval-audio.md §6.4 and setup-venv-chatterbox.md. .venv-piper is auto-created here
# (pure-CPU pip install) the same way scripts/submit-pl.sh does it; the two CUDA venvs are not
# (they need a specific torch wheel — see their setup docs). whisper-small/q8 is already cached
# in .hf-cache/ from every prior ASR run, so no model prefetch step is needed.
#
# Submit:  sbatch scripts/submit-unit-probe.sh
# Resume:  same command — synthesis skips existing <id>.wav, transcription skips existing ids.
set -euo pipefail

cd "$(dirname "$0")/.."
source scripts/athena-env.sh

# One results dir per job, committed after sync (audio dirs themselves are gitignored, so each
# engine's manifest.json — which carries the per-clip dur_s the analysis needs — is copied into
# RESULTS_DIR alongside the transcripts).
JOB="${SLURM_ARRAY_JOB_ID:-manual}"
RESULTS_DIR="eval/results/unit-probe-${JOB}"
PROBE_EN="$RESULTS_DIR/probe-en.json"
PROBE_PL="$RESULTS_DIR/probe-pl.json"
mkdir -p "$RESULTS_DIR"

# Regenerate the probe sets (deterministic; cheap; each lane needs only its own language but
# generating both is a no-op-cost safety net if lanes race on first run).
python3 scripts/generate-unit-probe.py "$PROBE_EN" --lang en
python3 scripts/generate-unit-probe.py "$PROBE_PL" --lang pl

TASK="${SLURM_ARRAY_TASK_ID:-0}"
case "$TASK" in
  0) ENGINE=qwen-en;          LANG=en; PROBE="$PROBE_EN"; VENV=.venv-qwen;       SYNTH="scripts/tts-qwen-1000.py" ;;
  1) ENGINE=piper-pl;         LANG=pl; PROBE="$PROBE_PL"; VENV=.venv-piper;      SYNTH="scripts/tts-piper-1000.py" ;;
  2) ENGINE=chatterbox-pl;    LANG=pl; PROBE="$PROBE_PL"; VENV=.venv-chatterbox; SYNTH="scripts/tts-chatterbox-1000-pl.py" ;;
  *) echo "unknown array task $TASK" >&2; exit 1 ;;
esac

AUDIO_DIR="eval/audio/unit-probe-${ENGINE}"
mkdir -p "$AUDIO_DIR"
echo "=== lane $TASK: engine=$ENGINE lang=$LANG audio=$AUDIO_DIR ==="

# --- Synthesis ---
if [ "$ENGINE" = "piper-pl" ] && [ ! -d "$VENV" ]; then
  echo "  .venv-piper not found — creating it (one-time; piper-tts is a small, pure-CPU install)"
  python3 -m venv "$VENV"
  source "$VENV/bin/activate"
  pip install --quiet --upgrade pip
  pip install --quiet piper-tts
else
  if [ ! -d "$VENV" ]; then
    echo "ERROR: $VENV not found — this engine's venv is CUDA-specific and must be set up first" >&2
    echo "       (docs/tts-eval-audio.md §6.4 for .venv-qwen, setup-venv-chatterbox.md for .venv-chatterbox)" >&2
    exit 1
  fi
  source "$VENV/bin/activate"
fi
python "$SYNTH" "$PROBE" "$AUDIO_DIR"
deactivate

# Copy the manifest (has per-clip dur_s) into the committed results dir for the local analyzer.
cp "$AUDIO_DIR/manifest.json" "$RESULTS_DIR/${ENGINE}-manifest.json"

# --- Transcription ---
# whisper-small/q8, BOTH prompted and un-prompted. The un-prompted run is the important one for
# this study: the DOMAIN_PROMPT deliberately biases output orthography toward `MeV`/`keV`, which
# is exactly the normalization that HIDES letter-spelled pronunciation — running without it gives
# letter-spell escapes (`M-E-V`) the best chance to surface as a secondary signal alongside the
# clip-duration measurement. A small model (rather than large-v3) is intentional here too: weaker
# decoders normalize less, so they leak the raw pronunciation more often.
MODEL=onnx-community/whisper-small
node scripts/asr-transcribe-manifest.mjs "$AUDIO_DIR" "$AUDIO_DIR/manifest.json" \
  "$MODEL" q8 "$RESULTS_DIR/${ENGINE}-small-q8-noprompt.json" --lang "$LANG" --no-prompt
node scripts/asr-transcribe-manifest.mjs "$AUDIO_DIR" "$AUDIO_DIR/manifest.json" \
  "$MODEL" q8 "$RESULTS_DIR/${ENGINE}-small-q8-prompt.json" --lang "$LANG"

echo "=== lane $TASK done: results in $RESULTS_DIR (${ENGINE}-*) ==="
echo "Sync back with:  rsync -av <athena>:.../aidedx/$RESULTS_DIR/ $RESULTS_DIR/"
echo "Then analyze locally:  python3 scripts/unit-probe-analyze.py $RESULTS_DIR"
